<?php include __DIR__ . '/partials/top.phtml' ?>

<div class="container">
    <h2 class="text-center">Delete item</h2>
    <form method="post">
        <p>Are you sure you want to delete the item <b><?= $item->getTitle() ?></b>?</p>
        <div class="text-right">
            <a class="btn btn-default" href="<?= $app->urlFor('items-list') ?>">Cancel</a>
            <button type="submit" class="btn btn-primary">Delete</button>
        </div>
    </form>
</div>

<?php include __DIR__ . '/partials/bottom.phtml' ?>